# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='subject',
        ),
    ]
