# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
